absl-py==0.11.0
ale-py==0.7.4
astunparse==1.6.3
autorom==0.4.2
autorom-accept-rom-license==0.4.2
black==21.9b0
box2d==2.3.10
cachetools==4.2.1
click==7.1.2
cloudpickle==1.6.0
cocos2d==0.6.5
cython==0.29.21
data==0.4
deepdish==0.3.6
dm-control==0.0.425341097
dm-env==1.5
dm-tree==0.1.6
docopt==0.6.2
fasteners==0.16
filelock==3.0.12
flatbuffers==1.12
funcsigs==1.0.2
future==0.18.2
future-fstrings==1.2.0
gast==0.3.3
glfw==2.0.0
google-auth==1.26.0
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
grpcio==1.32.0
gym==0.21.0
h5py==2.10.0
huggingface-hub==0.0.8
imageio==2.9.0
imageio-ffmpeg==0.4.3
importlib-metadata==4.11.2
importlib-resources==5.4.0
ipdb==0.13.4
jsonpickle==0.9.6
keras==2.8.0
keras-nightly==2.5.0.dev2021032900
keras-preprocessing==1.1.2
labmaze==1.0.3
libclang==13.0.0
lockfile==0.12.2
lxml==4.6.2
markdown==3.3.3
mujoco-py==2.1.2.14
munch==2.5.0
mypy-extensions==0.4.3
networkx==2.5
numexpr==2.7.3
numpy==1.20.1
oauthlib==3.1.0
opencv-python==4.5.1.48
opt-einsum==3.3.0
ordered-set==4.1.0
packaging==21.3
pathspec==0.9.0
patsy==0.5.2
pillow==7.2.0
pip==22.0.4
platformdirs==2.4.0
pot==0.8.1.0
protobuf==3.19.4
psutil==5.8.0
py-cpuinfo==8.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybullet==3.1.0
pycolab==1.2
pyglet==1.5.0
pylatex==1.4.1
pyopengl==3.1.5
pywavelets==1.1.1
regex==2021.4.4
requests-oauthlib==1.3.0
rsa==4.7
ruamel-yaml==0.16.12
ruamel-yaml-clib==0.2.2
sacred==0.7.4
sacremoses==0.0.45
scikit-image==0.18.1
setuptools==60.10.0
shutilwhich==1.1.0
statsmodels==0.13.2
tables==3.6.1
tabulate==0.8.9
tempdir==0.7.1
tensorboard==2.8.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardx==1.8
tensorflow==2.8.0
tensorflow-io-gcs-filesystem==0.24.0
termcolor==1.1.0
tf-estimator-nightly==2.8.0.dev2021122109
tifffile==2021.2.26
tokenize-rt==4.2.1
tokenizers==0.10.2
tomli==1.2.1
torch-tb-profiler==0.2.1
tqdm==4.59.0
typing-extensions==4.1.1
werkzeug==1.0.1
wrapt==1.12.1
